"""Alembic environment.

Async because everything else is (D-021). ``target_metadata`` is the same
``MetaData`` the repositories use, so autogenerate compares migrations against
the definitions the application actually runs on — the only arrangement where a
drift between the two is detectable.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.config import get_settings
from app.repositories.tables import NAMING_CONVENTION, metadata
from app.runtime import LOOP_FACTORY

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().async_database_url)

target_metadata = metadata


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Without these two, a type change or a server-default change produces
        # an empty autogenerated migration and the drift goes unnoticed.
        compare_type=True,
        compare_server_default=True,
        render_as_batch=False,
        **{"naming_convention": NAMING_CONVENTION},  # type: ignore[arg-type]
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a database — useful for review and for DBAs."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _run(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    engine = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with engine.connect() as connection:
        await connection.run_sync(_run)
    await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    # loop_factory, not the default: psycopg cannot use Windows' ProactorEventLoop.
    asyncio.run(run_migrations_online(), loop_factory=LOOP_FACTORY)
