"""The migration and the metadata must describe the same database.

Two sources of truth exist by construction (D-021): ``tables.py`` is what the
application queries against, migration 0001 is what actually gets created. They
are written separately on purpose — a migration has to replay the schema *as it
was*, which rules out generating it from today's metadata — and that is exactly
why they need a test holding them together.

This test needs no database: both sides are rendered to SQL offline. That
matters, because a schema mistake found at ``alembic upgrade`` time is found in
whatever environment happened to run it first.
"""

from __future__ import annotations

import io
import re
from contextlib import redirect_stdout
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app.repositories.tables import APP_ROLE, DEFAULT_ORGANIZATION_ID, metadata

ROOT = Path(__file__).resolve().parents[2]
MIGRATION = (
    ROOT / "backend" / "migrations" / "versions" / "0001_foundation_identity_and_data_identity.py"
)

# alembic's own bookkeeping table is not part of our schema.
IGNORED_TABLES = {"alembic_version"}


@pytest.fixture(scope="module")
def migration_sql() -> str:
    """Migration 0001 rendered to SQL without touching a database."""
    config = Config(str(ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(ROOT / "backend" / "migrations"))

    buffer = io.StringIO()
    with redirect_stdout(buffer):
        command.upgrade(config, "head", sql=True)
    return buffer.getvalue()


@pytest.fixture(scope="module")
def metadata_sql() -> str:
    """The same schema as ``tables.py`` describes it."""
    dialect = postgresql.dialect()  # type: ignore[no-untyped-call]
    parts = [str(CreateTable(table).compile(dialect=dialect)) for table in metadata.sorted_tables]
    parts += [
        str(CreateIndex(index).compile(dialect=dialect))
        for table in metadata.sorted_tables
        for index in table.indexes
    ]
    return "\n".join(parts)


def _tables(sql: str) -> set[str]:
    return set(re.findall(r"CREATE TABLE (\w+)", sql)) - IGNORED_TABLES


def _constraints(sql: str) -> set[str]:
    return {name for name in re.findall(r"CONSTRAINT (\w+)", sql) if "alembic" not in name}


def _indexes(sql: str) -> set[str]:
    return set(re.findall(r"CREATE INDEX (\w+)", sql))


def test_same_tables(migration_sql: str, metadata_sql: str) -> None:
    assert _tables(migration_sql) == _tables(metadata_sql)


def test_same_constraint_names(migration_sql: str, metadata_sql: str) -> None:
    """Names, not just shapes.

    A constraint whose name differs between the two sides is a constraint the
    next autogenerated migration will propose dropping and recreating — and the
    first version of this schema got that wrong, because the naming convention
    prefixes a name that was already prefixed.
    """
    assert _constraints(migration_sql) == _constraints(metadata_sql)


def test_same_indexes(migration_sql: str, metadata_sql: str) -> None:
    assert _indexes(migration_sql) == _indexes(metadata_sql)


def test_same_columns_per_table(migration_sql: str, metadata_sql: str) -> None:
    def columns_by_table(sql: str) -> dict[str, set[str]]:
        found: dict[str, set[str]] = {}
        for match in re.finditer(r"CREATE TABLE (\w+) \((.*?)\n\)", sql, flags=re.DOTALL):
            table = match.group(1)
            if table in IGNORED_TABLES:
                continue
            names = {
                line.strip().split()[0]
                for line in match.group(2).splitlines()
                if line.strip() and not line.strip().startswith("CONSTRAINT")
            }
            found[table] = names
        return found

    assert columns_by_table(migration_sql) == columns_by_table(metadata_sql)


# ------------------------------------------------- guarantees beyond DDL ----


@pytest.mark.invariant
def test_immutable_tables_have_update_triggers(migration_sql: str) -> None:
    """INV-2 and INV-3 in storage. The frozen dataclasses only cover this process."""
    for table in ("dataset_version", "schema_contract"):
        assert f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE ON {table}" in migration_sql


@pytest.mark.invariant
def test_audit_log_is_append_only(migration_sql: str) -> None:
    """§13.7: enforced by trigger, and again by grant."""
    assert "BEFORE UPDATE OR DELETE ON audit_event" in migration_sql
    assert f"GRANT SELECT, INSERT ON audit_event TO {APP_ROLE}" in migration_sql

    # The application role must never receive UPDATE or DELETE on the audit log.
    granted = re.findall(rf"GRANT ([A-Z, ]+) ON audit_event TO {APP_ROLE}", migration_sql)
    assert granted, "no grant found for audit_event"
    for grant in granted:
        assert "UPDATE" not in grant
        assert "DELETE" not in grant


@pytest.mark.invariant
def test_application_role_cannot_update_immutable_tables(migration_sql: str) -> None:
    for table in ("dataset_version", "schema_contract"):
        granted = re.findall(rf"GRANT ([A-Z, ]+) ON {table} TO {APP_ROLE}", migration_sql)
        assert granted, f"no grant found for {table}"
        for grant in granted:
            assert "UPDATE" not in grant


def test_default_organization_id_agrees_with_application_code() -> None:
    """The migration hardcodes the literal so history stays fixed; this keeps them in step."""
    source = MIGRATION.read_text(encoding="utf-8")
    assert str(DEFAULT_ORGANIZATION_ID) in source


def test_every_table_is_reachable_from_a_workspace() -> None:
    """Tenant isolation is a property of the schema before it is a property of code.

    Every table must either be a tenancy root (organization, app_user,
    user_session, login_attempt) or have a foreign-key path down to `workspace`.
    A table with no such path is a table `data_access.open()` cannot scope, and
    it would leak silently rather than loudly.
    """
    roots = {"organization", "app_user", "user_session", "login_attempt", "workspace"}
    resolved = set(roots)

    def parents(table: sa.Table) -> set[str]:
        return {fk.column.table.name for fk in table.foreign_keys}

    # Repeatedly admit tables all of whose parents are already reachable.
    for _ in range(len(metadata.tables)):
        for table in metadata.sorted_tables:
            if table.name in resolved:
                continue
            if parents(table) & resolved:
                resolved.add(table.name)

    unreachable = {t.name for t in metadata.sorted_tables} - resolved
    assert not unreachable, f"tables with no path to a workspace: {sorted(unreachable)}"
